{% set name = "cxxopts" %}
{% set version = "2.1.0" %}
{% set sha256 = "7672c79e5e48dd0cb1935c6efe65d2695d96fa764bf06c493d2db25a3cf633b4" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/jarro2783/cxxopts/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patch:
        - 0001-Fixup-integer-pattern-multiple-definition.patch

build:
    features:
        - vc14  # [win]
    number: 0
    skip: true  # [win and py<35]

requirements:
    build:
        - cmake
        - toolchain
    run:
        - vc 14  #[win]

test:
    commands:
        - if exist %LIBRARY_INC%\\cxxopts.hpp (exit 0) else (exit 1)                                    # [win]
        - if exist %LIBRARY_LIB%\\cmake\\cxxopts\\cxxopts-config.cmake (exit 0) else (exit 1)           # [win]
        - if exist %LIBRARY_LIB%\\cmake\\cxxopts\\cxxopts-config-version.cmake (exit 0) else (exit 1)   # [win]
        - test -f ${PREFIX}/include/cxxopts.hpp                                                         # [unix]
        - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config.cmake                                      # [unix]
        - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config-version.cmake                              # [unix]

about:
    description: This is a lightweight C++ option parser library, supporting the standard
        GNU style syntax for options.
    dev_url: https://github.com/jarro2783/cxxopts
    doc_url: https://github.com/jarro2783/cxxopts
    home: https://github.com/jarro2783/cxxopts
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A lightweight C++ option parser library

extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - JohanMabille
        - gouarin
